using = ['Bash', 'Docker']
gitRepoName = 'glue'
distroPackageName = 'glue'

name = "Edwin Kofler"
email = "edwin@kofler.dev"
project = "glue"
description = "Hypergeneral boilerplate manager and task runner for projects"
license = 'Apache-2.0'
